#!/usr/bin/perl

open(DIR, "<$ARGV[0]") or die "Unable to open $ARGV[0]: $!";

@TEMP = <DIR>;
chop @TEMP;
@DIR = `/usr/bin/find @TEMP`;
chop @DIR;

foreach $dir ( @DIR ) {
	@names = split("/", $dir);

	open(OUT, ">$names[@names-1].tag") or die "unable to open $names[@names-1]: $1";
	open(IN, "<$names[@names-1]") or die "unable to open $dir: $!";
	@lines = <IN>;
	chop @lines;chop @lines;

	for($i=0; $i < @lines; $i++){
		if ($lines[$i] =~ /^(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)$/){
			if( $i%2 == 0){
				push @TAGS, "<tr bgcolor=\"#DDEBF7\"><td>$1</td><td>$2</td><td>$3</td><td>$4</td><td>$5</td><td>$6</td><td>$7</td><td>$8</td><td>$9</td></tr>\n";
			}else{
				push @TAGS, "<tr><td>$1</td><td>$2</td><td>$3</td><td>$4</td><td>$5</td><td>$6</td><td>$7</td><td>$8</td><td>$9</td></tr>\n";
			}

			if( $4 eq "Office Hour" || $4 eq "office hour"){
				push @TAGS, "<tr bgcolor=\"#CCCCCC\" style=\"line-height:5px\"><td colspan=\"9\">&nbsp;</td></tr>\n";
			}
		}
	}
	grep(s/<td><\/td>/<td>&nspb;<\/td>/g, @TAGS);
	print OUT @TAGS;
}

